Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,20 +1,28 @@
-name: sendRequestToDeploy
+name: Deploy Frontend to VPN Server
+
 on:
+  workflow_dispatch:
   push:
     branches:
       - main
+
 jobs:
-  build:
-    name: sendrequest
-    runs-on: ubuntu-latest
+  deploy:
+    runs-on: linux
     steps:
-      - uses: convictional/trigger-workflow-and-wait@v1.3.0
-        with:
-          owner: BingChilling-INT221
-          repo: kw1_BingChilling_Infrastructure
-          github_token: ${{ secrets.G_ACCESS_TOKEN }}
-          workflow_file_name: deploy_vpn.yml
-      - name: Sended
+      - name: Run Deployment Script
         run: |
-          echo "Sended"
-          sleep 10s
+          # Enable "exit on error" behavior
+          set -e
+
+          # Navigate to the frontend directory
+          cd ${{ vars.frontend_dir }}  # Replace with the actual directory path
+
+          # Pull the latest changes from the repository
+          git pull
+
+          # Start the Docker services defined in the specified compose file
+          docker-compose -f ${{ vars.compose_file }} up -d  # Replace with the actual compose file path
+
+          # Provide feedback that the deployment process has started
+          echo "Frontend deployment process initiated."
