Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,6 +7,7 @@ on:
       - main
 env:
   frontend_dir: "/home/moniyom/kw1_BingChilling_Frontend/"
+  infrastructure_dir: "/home/moniyom/kw1_BingChilling_Infrastructure/"
   compose_file: "/home/moniyom/kw1_BingChilling_Infrastructure/compose.yaml"
 jobs:
   deploy_front:
@@ -28,3 +29,7 @@ jobs:
 
           # Provide feedback that the deployment process has started
           echo "Frontend deployment process initiated."
+      - name: Prune Docker
+        run: |
+          cd ${{ env.infrastructure_dir }}  # Navigate to the directory containing compose.yaml
+          docker system prune --all --volumes --force || echo "Prune command failed, but continuing..."
